mutation UserCreate($input: UserCreateInput!) {
  userCreate(input: $input) {
    ...UserData
  }
}

mutation UserUpdate($input: UserUpdateInput!) {
  userUpdate(input: $input) {
    ...UserData
  }
}

mutation UserDestroy($id: ID!) {
  userDestroy(id: $id)
}

mutation ChangePassword($input: ChangePasswordInput!) {
  changePassword(input: $input)
}

mutation UserAPIKeyCreate($input: UserAPIKeyCreateInput!) {
  userAPIKeyCreate(input: $input) {
    key
    api_key {
      ...UserAPIKeyData
    }
  }
}

mutation UserAPIKeyRevoke($id: ID!) {
  userAPIKeyRevoke(id: $id)
}

mutation UserCapabilitiesSet($input: UserCapabilitiesSetInput!) {
  userCapabilitiesSet(input: $input) {
    ...UserData
    ...UserCapabilityData
  }
}
